[package]
name = "db_core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
bytepack.workspace = true
ulid.workspace = true
chrono.workspace = true
dioxus-stores.workspace = true

chumsky.workspace = true


# wasmtime.workspace = true
# wasmtime = "43.0"
wasmi = "1.0"

wasmer.workspace = true
wasmer-types.workspace = true
wasm-encoder.workspace = true