[workspace]
resolver = "2"
members = ["ui", "desktop", "db", "bytepack", "query_parse", "db_core"]

[workspace.dependencies]
ui = { path = "ui" }
db = { path = "db" }
db_core = { path = "db_core" }
bytepack = { path = "bytepack" }
query_parse = { path = "query_parse" }

dioxus = "0.7.3"
dioxus-stores = "0.7.3"
dioxus-free-icons = { version = "0.10", features = [
    "font-awesome-brands",
    "font-awesome-regular",
    "font-awesome-solid",
] }
dioxus-clipboard = "0.3"
dioxus-use-js = "0.4"

serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"

ulid = "1.2.1"
chrono = "0.4"
thiserror = "2.0"

chumsky = { version = "1.0.0-alpha.8", features = ["pratt"] }

wasmer = "7.1"
wasmer-types = "7.1"
wasm-encoder = "0.246"


[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
